### PR TITLE
Updating plots.py

### PR DESCRIPTION
**Pull request by ethanhung11**
fixing up plots.py, added common.py for testing purposes (can remove later if unnecessary)

### CODE REVIEW

**Review by cyrillustan — CHANGES_REQUESTED** [review]
Look good in general. One thing: can you remove `ax[pos]` from the code? Using `ax` will be enough. The `pos` argument will actually break the code used by many other people.

**Comment by ethanhung11** [comment]
pos has been removed

**Review by cyrillustan — APPROVED** [review]
Screen Shot 2022-03-09 at 17 05 50
Thank you! A few things:
(1) Add titles to Q2X entry and Q2X chord plots (especially which one is which)
(2) It seems like many Q2X are negative. We should come up with a way to show these values (maybe use text to indicate the values below 0.0)
(3) In CP vs PCA comparison, the two bars overlap a lot. Move one of them a bit left and another a bit right.

After that, I think you can merge this PR. I have already approved it, so you can do it yourself.

**Comment by ethanhung11** [comment]
I've fixed the first and third issues, but for 2) how should I notate large negative values? The graphs graph the mean and standard mean error and do not actually show individual negative outliers. Is there a standard practice for this?

**Comment by cyrillustan** [comment]
You can leave the individual outliers alone. From what I see component >=3 are entirely blank, so we certainly need to make it better. Merge this PR first, and we can open a new one to solve this.

**Pull request merged**
