### PR TITLE
Add Tucker exploration to tensorpack

### PR DESCRIPTION
**Pull request by cyrillustan**
@Farnazmdi

### CODE REVIEW

**Comment by Farnazmdi** [comment]
The tucker is now added to the `Decomposition` class and the plot is added to the plot.py.  Unit test added to test_decompostion.py

**Review by aarmey — COMMENTED** [review]
Ok, I defer to @cyrillustan to review.

**Comment by Farnazmdi** [comment]
@cyrillustan I annotated the Tucker points. It doesn't look that nice. Do you want me to just annotate those [x,x,x] s?
image

**Comment by aarmey** [comment]
There's nothing special about the "same dims" Tucker points, so I feel a little weird highlighting them. Otherwise I think this is great.

**Pull request merged**
